[tools]
"aqua:YS-L/csvlens" = "latest"
bat = "latest"
bat-extras = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
llmfit = "latest"
lnav = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
auto_update = true
